import img10 from "../Movie images/10.jpg";
import img11 from "../Movie images/11.jpg";
import img12 from "../Movie images/12.jpg";
import img13 from "../Movie images/13.jpg";
import img14 from "../Movie images/14.jpg";
import img15 from "../Movie images/15.jpg";
import img16 from "../Movie images/16.jpg";
import img17 from "../Movie images/17.jpg";
import img18 from "../Movie images/18.jpg";
import img19 from "../Movie images/19.jpg";
import img20 from "../Movie images/20.jpg";
import img21 from "../Movie images/21.jpg";
import img22 from "../Movie images/22.jpg";
import img23 from "../Movie images/23.jpg";
import img24 from "../Movie images/24.jpg";
import img25 from "../Movie images/25.jpg";
import img26 from "../Movie images/26.jpg";
import img27 from "../Movie images/27.jpg";
import img28 from "../Movie images/28.jpg";
import img29 from "../Movie images/29.jpg";
import img30 from "../Movie images/30.jpg";
import img7 from "../Movie images/7.webp";
import img8 from "../Movie images/8.jpg";
import img9 from "../Movie images/9.jpg";
import img6 from "../Movie images/dori.jpg";
import img2 from "../Movie images/drakon1.jpg";
import img3 from "../Movie images/drakon2.webp";
import img4 from "../Movie images/drakon3.webp";
import img5 from "../Movie images/nemo.jpg";
import img1 from "../Movie images/ron.jpg";

const movieList = [
  {
    id: 1,
    name: "Неисправимый Рон",
    genre: ["Cartoon"],
    image: img1,
    type: "Cartoon",
    year: "2021",
    duration: "1h 46min",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Как приручить дракона",
    genre: ["Cartoon"],
    image: img2,
    type: "Cartoon",
    year: "2010",
    duration: "1h 38min",
    rating: "4",
  },
  {
    id: 3,
    name: "Как приручить дракона 2",
    genre: ["Cartoon"],
    image: img3,
    type: "Cartoon",
    year: "2014",
    duration: "1h 42min",
    rating: "4",
  },
  {
    id: 4,
    name: "Как приручить дракона 3",
    genre: ["Cartoon"],
    image: img4,
    type: "Cartoon",
    year: "2019",
    duration: "1h 44min",
    rating: "4",
  },
  {
    id: 5,
    name: "В поисках Немо",
    genre: ["Cartoon"],
    image: img5,
    type: "Cartoon",
    year: "2003",
    duration: "1h 40min",
    rating: "4",
  },
  {
    id: 6,
    name: "В поисках Дори",
    genre: ["Cartoon"],
    image: img6,
    type: "Cartoon",
    year: "2016",
    duration: "1h 37min",
    rating: "4",
  },
  {
    id: 7,
    name: "Законопослушный гражданин",
    genre: ["Action", "Drama"],
    image: img7,
    type: "Movie",
    year: "2009",
    duration: "1h 48min",
    rating: "4",
  },
  {
    id: 8,
    name: "Дом",
    genre: ["Documentary"],
    image: img8,
    type: "Movie",
    year: "2009",
    duration: "1h 52min",
    rating: "3.5",
  },
  {
    id: 9,
    name: "Голодные игры",
    genre: ["Action", "Fantasy"],
    image: img9,
    type: "Movie",
    year: "2012",
    duration: "2h 22min",
    rating: "3",
  },
  {
    id: 10,
    name: "Мандарины",
    genre: ["Drama", "Historical"],
    image: img10,
    type: "Movie",
    year: "2013",
    duration: "1h 27min",
    rating: "4.5",
  },
  {
    id: 11,
    name: "Отец солдата",
    genre: ["Drama", "Historical"],
    image: img11,
    type: "Movie",
    year: "1964",
    duration: "1h 32min",
    rating: "4.5",
  },
  {
    id: 12,
    name: "Фокус",
    genre: ["Drama"],
    image: img12,
    type: "Movie",
    year: "2015",
    duration: "1h 45min",
    actors: ["Will Smith"],
    rating: "4",
  },
  {
    id: 13,
    name: "Однажды в Америке",
    genre: ["Action"],
    image: img13,
    type: "Movie",
    year: "1984",
    duration: "4h 11min",
    actors: ["Robert De Niro"],
    rating: "3.5",
  },
  {
    id: 14,
    name: "Брюс Всемогущий",
    genre: ["Comedy"],
    image: img14,
    type: "Movie",
    year: "2003",
    duration: "1h 41min",
    actors: ["Jim Carrey"],
    rating: "4",
  },
  {
    id: 15,
    name: "Зима в огне",
    genre: ["Documentary", "Historical"],
    image: img15,
    type: "Movie",
    year: "2015",
    duration: "1h 42min",
    rating: "3.5",
  },
  {
    id: 16,
    name: "Схватка",
    genre: ["Action", "Drama"],
    image: img16,
    type: "Movie",
    year: "1995",
    duration: "2h 50min",
    actors: ["Robert De Niro, Al Pacino"],
    rating: "4",
  },
  {
    id: 17,
    name: "Адвокат дьявола",
    genre: ["Drama", "Christian"],
    image: img17,
    type: "Movie",
    year: "1997",
    duration: "2h 24min",
    actors: ["Al Pacino, Keanu Reeves"],
    rating: "4.5",
  },
  {
    id: 18,
    name: "Безумно влюблённый",
    genre: ["Comedy"],
    image: img18,
    type: "Movie",
    year: "1981",
    duration: "1h 42min",
    actors: ["Adriano Celentano"],
    rating: "3.5",
  },
  {
    id: 19,
    name: "Лицо со шрамом",
    genre: ["Action"],
    image: img19,
    type: "Movie",
    year: "1983",
    duration: "2h 50min",
    actors: ["Al Pacino"],
    rating: "3.5",
  },
  {
    id: 20,
    name: "Бойцовский клуб",
    genre: ["Action", "Drama"],
    image: img20,
    type: "Movie",
    year: "1999",
    duration: "2h 19min",
    actors: ["Brad Pitt"],
    rating: "5",
  },
  {
    id: 21,
    name: "Крёстный Отец 1",
    genre: ["Action", "Drama"],
    image: img21,
    type: "Movie",
    year: "1972",
    duration: "2h 55min",
    actors: ["Al Pacino"],
    rating: "5",
  },
  {
    id: 22,
    name: "Крёстный Отец 2",
    genre: ["Action", "Drama"],
    image: img22,
    type: "Movie",
    year: "1974",
    duration: "3h 22min",
    actors: ["Al Pacino, Robert De Niro"],
    rating: "5",
  },
  {
    id: 23,
    name: "Крёстный Отец 3",
    genre: ["Action", "Drama"],
    image: img23,
    type: "Movie",
    year: "1990",
    duration: "2h 42min",
    actors: ["Al Pacino"],
    rating: "5",
  },
  {
    id: 24,
    name: "Укрощение строптивого",
    genre: ["Comedy"],
    image: img24,
    type: "Movie",
    year: "1980",
    duration: "1h 44min",
    actors: ["Adriano Celentano"],
    rating: "4",
  },
  {
    id: 25,
    name: "Блеф",
    genre: ["Comedy"],
    image: img25,
    type: "Movie",
    year: "1976",
    duration: "1h 45min",
    actors: ["Adriano Celentano"],
    rating: "3.5",
  },
  {
    id: 26,
    name: "Нокдаун",
    genre: ["Drama"],
    image: img26,
    type: "Movie",
    year: "2005",
    duration: "2h 24min",
    actors: ["Russell Crowe"],
    rating: "4.5",
  },
  {
    id: 27,
    name: "Гладиатор",
    genre: ["Drama"],
    image: img27,
    type: "Movie",
    year: "2000",
    duration: "2h 35min",
    actors: ["Russell Crowe"],
    rating: "5",
  },
  {
    id: 28,
    name: "Последний самурай",
    genre: ["Drama"],
    image: img28,
    type: "Movie",
    year: "2003",
    duration: "2h 34min",
    actors: ["Tom Cruise"],
    rating: "5",
  },
  {
    id: 29,
    name: "Грань будущего",
    genre: ["Action", "Drama"],
    image: img29,
    type: "Movie",
    year: "2014",
    duration: "1h 53min",
    actors: ["Tom Cruise"],
    rating: "4",
  },
  {
    id: 30,
    name: "Обливион",
    genre: ["Action", "Drama"],
    image: img30,
    type: "Movie",
    year: "2013",
    duration: "2h 4min",
    actors: ["Tom Cruise"],
    rating: "4",
  },
];

export default movieList;
